# tasks file for logrotated
---
- name: install
  apt:
    name: "{{ logrotated_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - logrotated
    - logrotated-install

- name: update application-specific configuration files
  template:
    src: etc/logrotate.d/config.j2
    dest: "/etc/logrotate.d/{{ item.key }}"
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ logrotated_logrotate_d_files }}"
  tags:
    - configuration
    - logrotated
    - logrotated-configuration
    - logrotated-configuration-logrotate-d
